### ISSUE TITLE
Incorrect logo URL

### ISSUE THREAD

**Issue by daresh** [Oksydan/is_themecore#10]
It looks like since PrestaShop 1.7.7, the variable {$shop.logo} contains a full URL, causing an incorrect logo URL in the og and twitter tags, for example: "https://mpst.devhttps://mpst.dev/img/logo.png".

The same issue can also be observed in the ld+json section.

**Comment by Oksydan** [comment]
Hi @daresh,
thank you for your report. 
You are right, I am planing to release version 2.0 with multiple changes and almost complete refacto of that `ThemeStructuredJsonData` and `ThemeAssets` class.

**Comment by sq9kcq** [comment]
@daresh - Just edit 2 files:
is_themecore/views/template/hook/og-data.tpl
is_themecore/views/template/hook/twitter-data.tpl 

find: '{$urls.shop_domain_url}{$shop.logo}' and replace to: '{$shop.logo}'

**Comment by Oksydan** [comment]
Version 2.0 is during development available on branch 2.0. Unfortunately I don't have enough time recently to finish it.

**Comment by Oksydan** [comment]
Hi @daresh problem has been resolved with version 2.0.0 and it will be released soon.
I am closing this issue, feel free to create new one if you find any problem.
