### ISSUE TITLE
A better compatibility with core assets ?

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/is_themecore#17]
Hi, 
thanks for the theme and this idea of assets organised by resource and not by page its a great idea.

Do you think that you can improve the functionnality with the server: remote parameter option as mentionned in the official documentation of prestashop with something like in your file assets.yml :

js:
  myresource:
    fileName: //cdnjs.cloudflare.com/ajax/libs/mylib.js
    server: remote
    priority:60
    position:top

Thanks in advance for your answer.

**Comment by Oksydan** [comment]
Hi,
It is actually great idea. 
I will implement it in next 2.1 version.

**Comment by Oksydan** [comment]
Hi @Kandax86 

new version has been released with feature that allow you to register remote assets.
Thanks for your suggestion. 

I am closing this issue, feel free to open new one when you face an issue or come up with a great suggestion like this one.
