### ISSUE TITLE
Ability to add more pages to $listingPages

### ISSUE THREAD

**Issue by glukash** [Oksydan/is_themecore#23]
It would be nice to have an ability to add more pages to the $listingPages variable in Assets.php

**Comment by Oksydan** [comment]
Hi @glukash, 
What is your version of is_themecore? 
Is it below 2.0.0?

**Comment by glukash** [comment]
2.2.1

**Comment by Oksydan** [comment]
Hi @glukash,

I merged your PR to core but I thing thats bad idea to set that pages name somewhere is module.
I changed that check to check if controller is instance of `ProductListingFrontControllerCore`, every listing page have to extend it to work properly with all that listing updates etc. [Check it out](https://github.com/Oksydan/is_themecore/commit/8d9c50d3156d2f38a3479e46ac01a733316dfc61)

For now I am closing this issue feel free to open another.
